### ISSUE TITLE
fmw_domain::extension_jrf

### ISSUE THREAD

**Issue by janiemort** [oracle/fmw-chef-cookbook#11]
Hi,

The jrf.py that is generated when using the fmw_domain::extension_jrf makes a call to the following method:

getDatabaseDefaults()

This method does not appear to exist anywhere.  What should this method do?  Is there a way for me to provide the missing method?

Thanks,

Jane

**Comment by biemond** [comment]
Hi,

it depends if you are using wls 12.2 then you can use ADF/JRF restricted template this doesn't needs a DB repository else you need to make sure you create a standard RCU repository.

see https://github.com/oracle/chef-samples/tree/master/fmw_rcu

**Comment by janiemort** [comment]
Hi,

I did see that option to use the restricted template; however, the Oracle documentation says that for a production installation, the RCU configuration is required for both standalone and clustered domains. 

We are using Chef for production installations, not development. (I have forked these Chef cookbooks and modified them to install in "prod" server mode and added Nodemanager credential configuration so that nodemanager can still start up the AdminServer and managed servers.)

So for now, I plan to follow Oracle's requirement and use the internal database configuration. That being said, I repeat my original question:  "What does the missing getDatabaseDefaults() method do?  Is there a way for me to provide the missing method?"

Thanks,

Jane

**Comment by biemond** [comment]
yeah only for DEV but this domain you are creating with Chef is also only for DEV.
But when you add RCU to your chef attributes file it should be fine and work from the box.

what is does in WebLogic 12c it is using this datasource LocalSvcTblDataSource to retrieve all the RCU data and update all the datasources like OPSS , MDS etc connected to this RCU DB repository

```
        changeDatasource('LocalSvcTblDataSource', REPOS_DBUSER_PREFIX+'_STB', REPOS_DBPASSWORD, REPOS_DBURL)
        print 'Call getDatabaseDefaults which reads the service table'
        getDatabaseDefaults()
```

**Comment by janiemort** [comment]
Yes, I am modifying these cookbooks to provision PROD environments. 

The extention_jrf.rb is failing because there is no getDatabaseDefaults() method defined in the Chef cookbook.  I can create this missing method if I know what it is supposed to do.

**Comment by janiemort** [comment]
There is also a call to setServerGroups().  This method also does not exist.

**Comment by biemond** [comment]
I don't know what version you are using, but setServerGroups is part of wls in 12c.

**Comment by janiemort** [comment]
I am using version 12.2.1.1.0.  Thanks!

**Comment by biemond** [comment]
ok, if you don't have these jython methods then you probably got a classloading issue.
With 12.2.1 everything is loaded from the classpath and not from path <12.2.1

**Comment by janiemort** [comment]
So these jython methods are not part of the Chef samples cookbooks?  Where are they located?

**Comment by janiemort** [comment]
I'm running the cookbook again to verify the exact error.  I was just assuming that it failed because the methods do not exist in the cookbook python scripts.  When I run the jrf.py in the cookbook, I get no information about the error unfortunately.  Will run manually on the VM and see if I get more details about the error.

**Comment by biemond** [comment]
they are part of wls, did you install the wls infrastructure edition ( not the normal one)

**Comment by janiemort** [comment]
Yes I installed from the infrastructure jar using install_type = 'infra'  and ran the rcu::common which seems to have succeeded. However, when I run the jrf.py on the VM manually, I get the following exceptions which seems to indicate that perhaps the rcu recipe did not work?  Any idea how to troubleshoot this?

[oracle@default-redhat-68-7738330f ~]$ sh /opt/oracle/middleware_12211/oracle_common/comm
on/bin/wlst.sh /tmp/jrf.py xxx welcome1

Initializing WebLogic Scripting Tool (WLST) ...

Welcome to WebLogic Server Administration Scripting Shell

Type help() for help on available commands

Adding EM Template

Change datasource LocalScvTblDataSource for service table
Change datasource LocalSvcTblDataSource
Call getDatabaseDefaults which reads the service table
Error: getDatabaseDefaults() failed. Do dumpStack() to see details.
Error: runCmd() failed. Do dumpStack() to see details.
Problem invoking WLST - Traceback (innermost last):
  File "/tmp/jrf.py", line 44, in ?
  File "/tmp/WLSTOfflineIni1102967562167618696.py", line 253, in getDatabaseDefaults
  File "/tmp/WLSTOfflineIni1102967562167618696.py", line 19, in command
Failed to build JDBC Connection object:
        at com.oracle.cie.domain.script.jython.CommandExceptionHandler.handleException(Com
mandExceptionHandler.java:69)
        at com.oracle.cie.domain.script.jython.WLScriptContext.handleException(WLScriptCon
text.java:2666)
        at com.oracle.cie.domain.script.jython.WLScriptContext.runCmd(WLScriptContext.java
:698)
        at sun.reflect.GeneratedMethodAccessor616.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.ja
va:43)
        at java.lang.reflect.Method.invoke(Method.java:498)

com.oracle.cie.domain.script.jython.WLSTException: com.oracle.cie.domain.script.jython.WLS
TException: Got exception when auto configuring the schema component(s) with data obtained
 from shadow table:
Failed to build JDBC Connection object:

**Comment by janiemort** [comment]
I commented out all of the recipes except for the infrastructure install and the rcu::common.  The output from test kitchen is below and it looks like it was successful; however, the rcu recipe did not create the tables in the Oracle db.  Not sure if this is why the getDatabaseTables() method fails or not. I logged into the VM to run the rcu command manually, but the rcu input .py file is not in the tmp directory, so not sure how to test this.  Any help would be appreciated. 

```
   Recipe: fmw_rcu::common
     * cookbook_file[/tmp/checkrcu.py] action create
       - create new file /tmp/checkrcu.py
       - update content in file /tmp/checkrcu.py from none to cba312
       --- /tmp/checkrcu.py 2016-10-13 15:06:26.610256024 -0500
       +++ /tmp/.checkrcu.py20161013-3123-2j0c8t    2016-10-13 15:06:26.609256017 -050
```

0
           @@ -1 +1,25 @@
           +from java.sql import DriverManager
           +
           +jdbcurl  = sys.argv[1]
           +password = sys.argv[2]
           +prefix   = sys.argv[3]
           +sysuser  = sys.argv[4]
           +
           +conn = DriverManager.getConnection(jdbcurl, sysuser + " as sysdba", password)
           +stmt = conn.createStatement()
           +try:
           +    rs = stmt.executeQuery("select distinct 'found' from system.schema_version
_registry where mrc_name ='"+prefix+"'")
           +
           +    emp = {}
           +    while rs.next():
           +      print rs.getString(1)
           +
           +    rs.close()
           +    stmt.close()
           +    conn.close()
           +
           +except:
           +    print "rcu table does not exists"
           +    stmt.close()
           +    conn.close()
           - change mode from '' to '0775'
           - change owner from '' to 'oracle'
           - change group from '' to 'oinstall'
           - restore selinux security context
         \* fmw_rcu_repository[PME_DEV] action create
           - Create resource fmw_rcu_repository[PME_DEV]
         \* execute[Create PME_DEV] action run
           - execute /opt/oracle/middleware_12211/oracle_common/bin/rcu -silent -createRep
ository -databaseType ORACLE -connectString 1pldrpmedb02.main.usfood.com:1521 -dbUser PMEA
FADM -dbRole SYSDBA  -schemaPrefix PME_DEV  -component MDS -component IAU -component IAU_A
PPEND -component IAU_VIEWER -component OPSS -component WLS -component STB -component UCSUM
S -f < /tmp/rcu_input20161013-3123-1smkvc9.py

```
   Running handlers:
   Running handlers complete
   Chef Client finished, 26/32 resources updated in 07 minutes 27 seconds
   Finished converging <default-redhat-68> (7m56.72s).
```

**Comment by biemond** [comment]
When this fails it is probably because the chef, databag  rcu db parameters are not correct. This is very strict with db, jdbc URL & service name etc, don't use Sid.

Also check the service table of the datasource , the rcu scheme entries should be there  with valid jdbc urls. Sometimes this tables contains strange jdbc urls

**Comment by janiemort** [comment]
Thanks very much for your reply.  I really appreciate your patience!  

At first I had specified the SID and got an error.  I changed it and the error went away.  Now I get no error at all and no tables are created.  Can you tell me what goes in the rcu input file so I can create one manually and run the rcu command manually to see what the errors are?

**Comment by janiemort** [comment]
I was able to get the fmw_rcu to work; however, my jrf.py is still failing.  I added a dumpStack() and am getting more information about the failure.  

Where are the sample JDBC URLs in the error below coming from?

```
   Error: runCmd() failed. Do dumpStack() to see details.
   STDERR: com.oracle.cie.domain.script.jython.WLSTException: Got exception when auto
```

configuring the schema component(s) with data obtained from shadow table:
       Failed to build JDBC Connection object:
        at com.oracle.cie.domain.script.jython.CommandExceptionHandler.handleException(Com
mandExceptionHandler.java:69)
        at com.oracle.cie.domain.script.jython.WLScriptContext.handleException(WLScriptCon
text.java:2666)
        at com.oracle.cie.domain.script.jython.WLScriptContext.runCmd(WLScriptContext.java
:698)
        at sun.reflect.GeneratedMethodAccessor616.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.ja
va:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.python.core.PyReflectedFunction.**call**(Unknown Source)
        at org.python.core.PyMethod.**call**(Unknown Source)
        at org.python.core.PyObject.**call**(Unknown Source)
        at org.python.core.PyInstance.invoke(Unknown Source)
        at org.python.pycode._pyx5.command$1(/tmp/WLSTOfflineIni7149329094671874870.py:19)

```
    at org.python.pycode._pyx5.call_function(/tmp/WLSTOfflineIni7149329094671874870.py
```

)
        at org.python.core.PyTableCode.call(Unknown Source)
        at org.python.core.PyTableCode.call(Unknown Source)
        at org.python.core.PyTableCode.call(Unknown Source)
        at org.python.core.PyFunction.**call**(Unknown Source)
        at org.python.pycode._pyx5.getDatabaseDefaults$67(/tmp/WLSTOfflineIni7149329094671
874870.py:253)
        at org.python.pycode._pyx5.call_function(/tmp/WLSTOfflineIni7149329094671874870.py
)
        at org.python.core.PyTableCode.call(Unknown Source)
        at org.python.core.PyTableCode.call(Unknown Source)
        at org.python.core.PyTableCode.call(Unknown Source)
        at org.python.core.PyFunction.__call__(Unknown Source)
        at org.python.pycode._pyx98.f$0(/tmp/jrf.py:47)
        at org.python.pycode._pyx98.call_function(/tmp/jrf.py)
        at org.python.core.PyTableCode.call(Unknown Source)
        at org.python.core.PyCode.call(Unknown Source)
        at org.python.core.Py.runCode(Unknown Source)
        at org.python.util.PythonInterpreter.execfile(Unknown Source)
        at weblogic.management.scripting.WLST.main(WLST.java:181)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.ja
va:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at weblogic.WLST.main(WLST.java:47)
       Caused by: com.oracle.cie.domain.script.ScriptException: Got exception when auto co
nfiguring the schema component(s) with data obtained from shadow table:
       Failed to build JDBC Connection object:
        at com.oracle.cie.domain.script.jython.WLSTState.processCommand(WLSTState.java:241
)
        at com.oracle.cie.domain.script.jython.WLScriptContext.runCmd(WLScriptContext.java
:692)
        ... 31 more
       Caused by: com.oracle.cie.domain.script.jython.WLSTException: Got exception when au
to configuring the schema component(s) with data obtained from shadow table:
       Failed to build JDBC Connection object:
        at com.oracle.cie.domain.script.jython.CommandExceptionHandler.handleException(Com
mandExceptionHandler.java:69)
        at com.oracle.cie.domain.script.jython.WLScriptContext.handleException(WLScriptCon
text.java:2666)
        at com.oracle.cie.domain.script.jython.WLScriptContext.getDatabaseDefaults(WLScrip
tContext.java:3681)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.ja
va:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.oracle.cie.domain.script.jython.WLSTState.processCommand(WLSTState.java:224
)
        ... 32 more
       Caused by: com.oracle.cie.domain.script.ScriptException: Got exception when auto co
nfiguring the schema component(s) with data obtained from shadow table:
       Failed to build JDBC Connection object:
        at com.oracle.cie.domain.script.ScriptExecutor.getDatabaseDefaults(ScriptExecutor.
java:3544)
        at com.oracle.cie.domain.script.jython.WLScriptContext.getDatabaseDefaults(WLScrip
tContext.java:3677)
        ... 37 more
       Caused by: com.oracle.cie.common.CommonException: Failed to build JDBC Connection o
bject:
       Root Cause: java.lang.Exception: Datasource LocalSvcTblDataSource: The value of use
rname is not specified. It has a null value.
        at com.oracle.cie.domain.jdbc.CommonDBHelper.bindShadowTableData(CommonDBHelper.ja
va:663)
        at com.oracle.cie.domain.script.ScriptExecutor.getDatabaseDefaults(ScriptExecutor.
java:3519)
        ... 38 more
       Problem invoking WLST - Traceback (innermost last):
         File "/tmp/jrf.py", line 59, in ?
         File "/tmp/WLSTOfflineIni7149329094671874870.py", line 135, in updateDomain
         File "/tmp/WLSTOfflineIni7149329094671874870.py", line 19, in command
       64254: Error occurred in "OPSS Processing" phase execution
       64254: Encountered error: SecurityContext:
        Domain Name: pme_domain_dev
        JDBC URL: opss-audit-DBDS:jdbc:oracle:thin:@//dbhost.example.com:1521/orcl
        JDBC URL: opss-data-source:jdbc:oracle:thin:@//dbhost.example.com:1521/orcl
        JNDI Name: opss-audit-DBDS:jdbc/AuditAppendDataSource
        JNDI Name: opss-data-source:jdbc/OpssDataSource
        Driver Name: opss-audit-DBDS:oracle.jdbc.OracleDriver
        Driver Name: opss-data-source:oracle.jdbc.OracleDriver
        Persistence Type: DATABASE
        Platform: WLS
        Scratch Dir: scratch
        Reconfig Domain: false
        Shared Secret Store: null
        Extension: true
        DisableManagementOperations: falseJDBC Properties:
       user:DEV_IAU_APPEND
       username:DEV_IAU_APPENDJDBC Properties:
       user:DEV_OPSS
       username:DEV_OPSS
       64254: Check log for more detail.

```
    at com.oracle.cie.domain.script.jython.CommandExceptionHandler.handleException(Com
```

mandExceptionHandler.java:69)
        at com.oracle.cie.domain.script.jython.WLScriptContext.handleException(WLScriptCon
text.java:2666)
        at com.oracle.cie.domain.script.jython.WLScriptContext.runCmd(WLScriptContext.java
:698)
        at sun.reflect.GeneratedMethodAccessor616.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.ja
va:43)
        at java.lang.reflect.Method.invoke(Method.java:498)

```
   com.oracle.cie.domain.script.jython.WLSTException: com.oracle.cie.domain.script.jyt
```

hon.WLSTException: Error updating domain:
       64254: Error occurred in "OPSS Processing" phase execution
       64254: Encountered error: SecurityContext:
        Domain Name: pme_domain_dev
        JDBC URL: opss-audit-DBDS:jdbc:oracle:thin:@//dbhost.example.com:1521/orcl
        JDBC URL: opss-data-source:jdbc:oracle:thin:@//dbhost.example.com:1521/orcl
        JNDI Name: opss-audit-DBDS:jdbc/AuditAppendDataSource
        JNDI Name: opss-data-source:jdbc/OpssDataSource
        Driver Name: opss-audit-DBDS:oracle.jdbc.OracleDriver
        Driver Name: opss-data-source:oracle.jdbc.OracleDriver
        Persistence Type: DATABASE
        Platform: WLS
        Scratch Dir: scratch
        Reconfig Domain: false
        Shared Secret Store: null
        Extension: true
        DisableManagementOperations: falseJDBC Properties:
       user:DEV_IAU_APPEND
       username:DEV_IAU_APPENDJDBC Properties:
       user:DEV_OPSS
       username:DEV_OPSS
       64254: Check log for more detail.
       ---- End output of su - oracle -c 'export CONFIG_JVM_ARGS=-Djava.security.egd=file:
/dev/./urandom;/opt/oracle/middleware_12211/wlserver/../oracle_common/common/bin/wlst.sh -
skipWLSModuleScanning /tmp/jrf.py xxx welcome1' ----
       Ran su - oracle -c 'export CONFIG_JVM_ARGS=-Djava.security.egd=file:/dev/./urandom;
/opt/oracle/middleware_12211/wlserver/../oracle_common/common/bin/wlst.sh -skipWLSModuleSc
anning /tmp/jrf.py xxx welcome1' returned 1
       [2016-10-18T12:59:32-05:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run p
rocess exited unsuccessfully (exit code 1)

**Comment by janiemort** [comment]
After making some corrections to the URL configurations, I was able to get this to work.

**Comment by TarakChadaram** [comment]
@janiemort can you please let us know what corrections you did in the URL. I am running into the same.
Please share.

Regards,
Tarak.

**Comment by janiemort** [comment]
If I remember correctly, I believe I had the same value for jdbc_database_url as I had for db_database_url.  I followed Edward's example below and it fixed my problem. 

     "jdbc_database_url":      "jdbc:oracle:thin:@10.10.10.15:1521/soarepos.example.com",
     "db_database_url":        "10.10.10.15:1521:soarepos.example.com",
